#include "qcommon/q_shared.hpp"
#include "rd-common/tr_common.hpp"
#include "rd-vanilla/tr_cvars.hpp"

#ifdef _DEBUG
cvar_t *r_noPrecacheGLA;
#endif

cvar_t *broadsword;
cvar_t *broadsword_dircap;
cvar_t *broadsword_dontstopanim;
cvar_t *broadsword_effcorr;
cvar_t *broadsword_extra1;
cvar_t *broadsword_extra2;
cvar_t *broadsword_kickbones;
cvar_t *broadsword_kickorigin;
cvar_t *broadsword_playflop;
cvar_t *broadsword_ragtobase;
cvar_t *broadsword_smallbbox;
cvar_t *broadsword_waitforshot;
cvar_t *cg_g2MarksAllModels;
cvar_t *cg_shadows;
cvar_t *cl_running;
cvar_t *com_buildScript;
cvar_t *dedicated;
cvar_t *r_allowExtensions;
cvar_t *r_ambientScale;
cvar_t *r_aspectCorrectFonts;
cvar_t *r_autolodscalevalue;
cvar_t *r_autoMap;
cvar_t *r_autoMapBackAlpha;
cvar_t *r_autoMapDisable;
cvar_t *r_aviMotionJpegQuality;
cvar_t *r_clear;
cvar_t *r_colorMipLevels;
cvar_t *r_cullRoofFaces;
cvar_t *r_debugLight;
cvar_t *r_debugSort;
cvar_t *r_debugSurface;
cvar_t *r_detailTextures;
cvar_t *r_directedScale;
cvar_t *r_displayRefresh;
cvar_t *r_dlightStyle;
cvar_t *r_drawentities;
cvar_t *r_drawfog;
cvar_t *r_drawSun;
cvar_t *r_drawTerrain;
cvar_t *r_drawworld;
cvar_t *r_DynamicGlow;
cvar_t *r_DynamicGlowDelta;
cvar_t *r_DynamicGlowHeight;
cvar_t *r_DynamicGlowIntensity;
cvar_t *r_DynamicGlowPasses;
cvar_t *r_DynamicGlowSoft;
cvar_t *r_DynamicGlowWidth;
cvar_t *r_dynamiclight;
cvar_t *r_environmentMapping;
cvar_t *r_ext_compiled_vertex_array;
cvar_t *r_ext_compress_lightmaps;
cvar_t *r_ext_compress_textures;
cvar_t *r_ext_gamma_control;
cvar_t *r_ext_multitexture;
cvar_t *r_ext_preferred_tc_method;
cvar_t *r_ext_texture_env_add;
cvar_t *r_ext_texture_filter_anisotropic;
cvar_t *r_facePlaneCull;
cvar_t *r_fastsky;
cvar_t *r_finish;
cvar_t *r_flares;
cvar_t *r_fullbright;
cvar_t *r_fullscreen;
cvar_t *r_gamma;
cvar_t *r_gammaShaders;
cvar_t *r_Ghoul2AnimSmooth;
cvar_t *r_Ghoul2UnSqashAfterSmooth;
cvar_t *r_ignore;
cvar_t *r_ignoreGLErrors;
cvar_t *r_inGameVideo;
cvar_t *r_intensity;
cvar_t *r_lightmap;
cvar_t *r_lockpvs;
cvar_t *r_lodbias;
cvar_t *r_lodCurveError;
cvar_t *r_lodscale;
cvar_t *r_logFile;
cvar_t *r_mapOverBrightBits;
cvar_t *r_markcount;
cvar_t *r_marksOnTriangleMeshes;
cvar_t *r_maxpolys;
cvar_t *r_maxpolyverts;
cvar_t *r_mode;
cvar_t *r_measureOverdraw;
cvar_t *r_modelpoolmegs;
cvar_t *r_nobind;
cvar_t *r_noborder;
cvar_t *r_nocull;
cvar_t *r_nocurves;
cvar_t *r_noportals;
cvar_t *r_norefresh;
cvar_t *r_noServerGhoul2;
cvar_t *r_novis;
cvar_t *r_offsetFactor;
cvar_t *r_offsetUnits;
cvar_t *r_overBrightBits;
cvar_t *r_picmip;
cvar_t *r_portalOnly;
cvar_t *r_primitives;
cvar_t *r_roofCeilFloorDist;
cvar_t *r_roofCullCeilDist;
cvar_t *r_screenshotJpegQuality;
cvar_t *r_shadowRange;
cvar_t *r_showcluster;
cvar_t *r_showFrameVariance;
cvar_t *r_showImages;
cvar_t *r_shownormals;
cvar_t *r_showsky;
cvar_t *r_showtris;
cvar_t *r_simpleMipMaps;
cvar_t *r_singleShader;
cvar_t *r_skipBackEnd;
cvar_t *r_speeds;
cvar_t *r_subdivisions;
cvar_t *r_surfaceSprites;
cvar_t *r_surfaceWeather;
cvar_t *r_terrainTessellate;
cvar_t *r_terrainWaterOffset;
cvar_t *r_texturebits;
cvar_t *r_texturebitslm;
cvar_t *r_textureMode;
cvar_t *r_uiFullScreen;
cvar_t *r_verbose;
cvar_t *r_vertexLight;
cvar_t *r_windAngle;
cvar_t *r_windDampFactor;
cvar_t *r_windGust;
cvar_t *r_windPointForce;
cvar_t *r_windPointX;
cvar_t *r_windPointY;
cvar_t *r_windSpeed;
cvar_t *r_znear;
cvar_t *se_language;
cvar_t *sv_pure;
cvar_t *timescale;

void R_InitCvars( void ) {
	#ifdef _DEBUG
	r_noPrecacheGLA =                  ri.Cvar_Get( "r_noPrecacheGLA",                  "0",                              CVAR_CHEAT,                    "" );
	#endif

	broadsword =                       ri.Cvar_Get( "broadsword",                       "0",                              CVAR_ARCHIVE_ND,               "" );
	broadsword_dircap =                ri.Cvar_Get( "broadsword_dircap",                "64",                             CVAR_NONE,                     "" );
	broadsword_dontstopanim =          ri.Cvar_Get( "broadsword_dontstopanim",          "0",                              CVAR_NONE,                     "" );
	broadsword_effcorr =               ri.Cvar_Get( "broadsword_effcorr",               "1",                              CVAR_NONE,                     "" );
	broadsword_extra1 =                ri.Cvar_Get( "broadsword_extra1",                "0",                              CVAR_NONE,                     "" );
	broadsword_extra2 =                ri.Cvar_Get( "broadsword_extra2",                "0",                              CVAR_NONE,                     "" );
	broadsword_kickbones =             ri.Cvar_Get( "broadsword_kickbones",             "1",                              CVAR_NONE,                     "" );
	broadsword_kickorigin =            ri.Cvar_Get( "broadsword_kickorigin",            "1",                              CVAR_NONE,                     "" );
	broadsword_playflop =              ri.Cvar_Get( "broadsword_playflop",              "1",                              CVAR_NONE,                     "" );
	broadsword_ragtobase =             ri.Cvar_Get( "broadsword_ragtobase",             "2",                              CVAR_NONE,                     "" );
	broadsword_smallbbox =             ri.Cvar_Get( "broadsword_smallbbox",             "0",                              CVAR_NONE,                     "" );
	broadsword_waitforshot =           ri.Cvar_Get( "broadsword_waitforshot",           "0",                              CVAR_NONE,                     "" );
	cg_g2MarksAllModels =              ri.Cvar_Get( "cg_g2MarksAllModels",              "0",                              CVAR_NONE,                     "" );
	cg_shadows =                       ri.Cvar_Get( "cg_shadows",                       "1",                              CVAR_NONE,                     "" );
	cl_running =                       ri.Cvar_Get( "cl_running",                       "",                               CVAR_NONE,                     "" );
	com_buildScript =                  ri.Cvar_Get( "com_buildScript",                  "0",                              CVAR_NONE,                     "" );
	dedicated =                        ri.Cvar_Get( "dedicated",                        "0",                              CVAR_NONE,                     "" );
	r_allowExtensions =                ri.Cvar_Get( "r_allowExtensions",                "1",                              CVAR_ARCHIVE_ND | CVAR_LATCH,  "" );
	r_ambientScale =                   ri.Cvar_Get( "r_ambientScale",                   "0.6",                            CVAR_CHEAT,                    "" );
	r_aspectCorrectFonts =             ri.Cvar_Get( "r_aspectCorrectFonts",             "0",                              CVAR_ARCHIVE,                  "" );
	r_autolodscalevalue =              ri.Cvar_Get( "r_autolodscalevalue",              "0",                              CVAR_ROM,                      "" );
	r_autoMap =                        ri.Cvar_Get( "r_autoMap",                        "0",                              CVAR_ARCHIVE_ND,               "" ); //automap renderside toggle for debugging -rww
	r_autoMapBackAlpha =               ri.Cvar_Get( "r_autoMapBackAlpha",               "0",                              CVAR_NONE,                     "" ); //alpha of automap bg -rww
	r_autoMapDisable =                 ri.Cvar_Get( "r_autoMapDisable",                 "1",                              CVAR_NONE,                     "" );
	r_aviMotionJpegQuality =           ri.Cvar_Get( "r_aviMotionJpegQuality",           "90",                             CVAR_ARCHIVE_ND,               "" );
	r_clear =                          ri.Cvar_Get( "r_clear",                          "0",                              CVAR_CHEAT,                    "" );
	r_colorMipLevels =                 ri.Cvar_Get( "r_colorMipLevels",                 "0",                              CVAR_LATCH,                    "" );
	r_cullRoofFaces =                  ri.Cvar_Get( "r_cullRoofFaces",                  "0",                              CVAR_CHEAT,                    "" ); //attempted smart method of culling out upwards facing surfaces on roofs for automap shots -rww
	r_debugLight =                     ri.Cvar_Get( "r_debugLight",                     "0",                              CVAR_TEMP,                     "" );
	r_debugSort =                      ri.Cvar_Get( "r_debugSort",                      "0",                              CVAR_CHEAT,                    "" );
	r_debugSurface =                   ri.Cvar_Get( "r_debugSurface",                   "0",                              CVAR_CHEAT,                    "" );
	r_detailTextures =                 ri.Cvar_Get( "r_detailTextures",                 "1",                              CVAR_ARCHIVE_ND | CVAR_LATCH,  "" );
	r_directedScale =                  ri.Cvar_Get( "r_directedScale",                  "1",                              CVAR_CHEAT,                    "" );
	r_displayRefresh =                 ri.Cvar_Get( "r_displayRefresh",                 "0",                              CVAR_LATCH,                    "" );
	r_dlightStyle =                    ri.Cvar_Get( "r_dlightStyle",                    "1",                              CVAR_TEMP,                     "" );
	r_drawentities =                   ri.Cvar_Get( "r_drawentities",                   "1",                              CVAR_CHEAT,                    "" );
	r_drawfog =                        ri.Cvar_Get( "r_drawfog",                        "2",                              CVAR_CHEAT,                    "" );
	r_drawSun =                        ri.Cvar_Get( "r_drawSun",                        "0",                              CVAR_ARCHIVE_ND,               "" );
	r_drawTerrain =                    ri.Cvar_Get( "r_drawTerrain",                    "1",                              CVAR_CHEAT,                    "" );
	r_drawworld =                      ri.Cvar_Get( "r_drawworld",                      "1",                              CVAR_CHEAT,                    "" );
	r_DynamicGlow =                    ri.Cvar_Get( "r_DynamicGlow",                    "0",                              CVAR_ARCHIVE_ND,               "" );
	r_DynamicGlowDelta =               ri.Cvar_Get( "r_DynamicGlowDelta",               "0.8f",                           CVAR_ARCHIVE_ND,               "" );
	r_DynamicGlowHeight =              ri.Cvar_Get( "r_DynamicGlowHeight",              "240",                            CVAR_ARCHIVE_ND | CVAR_LATCH,  "" );
	r_DynamicGlowIntensity =           ri.Cvar_Get( "r_DynamicGlowIntensity",           "1.13f",                          CVAR_ARCHIVE_ND,               "" );
	r_DynamicGlowPasses =              ri.Cvar_Get( "r_DynamicGlowPasses",              "5",                              CVAR_ARCHIVE_ND,               "" );
	r_DynamicGlowSoft =                ri.Cvar_Get( "r_DynamicGlowSoft",                "1",                              CVAR_ARCHIVE_ND,               "" );
	r_DynamicGlowWidth =               ri.Cvar_Get( "r_DynamicGlowWidth",               "320",                            CVAR_ARCHIVE_ND | CVAR_LATCH,  "" );
	r_dynamiclight =                   ri.Cvar_Get( "r_dynamiclight",                   "1",                              CVAR_ARCHIVE,                  "" );
	r_environmentMapping =             ri.Cvar_Get( "r_environmentMapping",             "1",                              CVAR_ARCHIVE_ND,               "" );
	r_ext_compiled_vertex_array =      ri.Cvar_Get( "r_ext_compiled_vertex_array",      "1",                              CVAR_ARCHIVE_ND | CVAR_LATCH,  "" );
	r_ext_compress_lightmaps =         ri.Cvar_Get( "r_ext_compress_lightmaps",         "0",                              CVAR_ARCHIVE_ND | CVAR_LATCH,  "" );
	r_ext_compress_textures =          ri.Cvar_Get( "r_ext_compress_textures",          "1",                              CVAR_ARCHIVE_ND | CVAR_LATCH,  "" );
	r_ext_gamma_control =              ri.Cvar_Get( "r_ext_gamma_control",              "1",                              CVAR_ARCHIVE_ND | CVAR_LATCH,  "" );
	r_ext_multitexture =               ri.Cvar_Get( "r_ext_multitexture",               "1",                              CVAR_ARCHIVE_ND | CVAR_LATCH,  "" );
	r_ext_preferred_tc_method =        ri.Cvar_Get( "r_ext_preferred_tc_method",        "0",                              CVAR_ARCHIVE_ND | CVAR_LATCH,  "" );
	r_ext_texture_env_add =            ri.Cvar_Get( "r_ext_texture_env_add",            "1",                              CVAR_ARCHIVE_ND | CVAR_LATCH,  "" );
	r_ext_texture_filter_anisotropic = ri.Cvar_Get( "r_ext_texture_filter_anisotropic", "16",                             CVAR_ARCHIVE_ND,               "" );
	r_facePlaneCull =                  ri.Cvar_Get( "r_facePlaneCull",                  "1",                              CVAR_ARCHIVE_ND,               "" );
	r_fastsky =                        ri.Cvar_Get( "r_fastsky",                        "0",                              CVAR_ARCHIVE_ND,               "" );
	r_finish =                         ri.Cvar_Get( "r_finish",                         "0",                              CVAR_ARCHIVE_ND,               "" );
	r_flares =                         ri.Cvar_Get( "r_flares",                         "1",                              CVAR_ARCHIVE_ND,               "" );
	r_fullbright =                     ri.Cvar_Get( "r_fullbright",                     "0",                              CVAR_CHEAT,                    "" );
	r_fullscreen =                     ri.Cvar_Get( "r_fullscreen",                     "0",                              CVAR_ARCHIVE | CVAR_LATCH,     "" );
	r_gamma =                          ri.Cvar_Get( "r_gamma",                          "1",                              CVAR_ARCHIVE_ND,               "" );
	r_gammaShaders =                   ri.Cvar_Get( "r_gammaShaders",                   "0",                              CVAR_ARCHIVE_ND | CVAR_LATCH,  "" );
	r_Ghoul2AnimSmooth =               ri.Cvar_Get( "r_Ghoul2AnimSmooth",               "0.3",                            CVAR_NONE,                     "" );
	r_Ghoul2UnSqashAfterSmooth =       ri.Cvar_Get( "r_Ghoul2UnSqashAfterSmooth",       "1",                              CVAR_NONE,                     "" );
	r_ignore =                         ri.Cvar_Get( "r_ignore",                         "1",                              CVAR_CHEAT,                    "" );
	r_ignoreGLErrors =                 ri.Cvar_Get( "r_ignoreGLErrors",                 "1",                              CVAR_ARCHIVE_ND,               "" );
	r_inGameVideo =                    ri.Cvar_Get( "r_inGameVideo",                    "1",                              CVAR_ARCHIVE_ND,               "" );
	r_intensity =                      ri.Cvar_Get( "r_intensity",                      "1",                              CVAR_LATCH,                    "" );
	r_lightmap =                       ri.Cvar_Get( "r_lightmap",                       "0",                              CVAR_CHEAT,                    "" );
	r_lockpvs =                        ri.Cvar_Get( "r_lockpvs",                        "0",                              CVAR_CHEAT,                    "" );
	r_lodbias =                        ri.Cvar_Get( "r_lodbias",                        "0",                              CVAR_ARCHIVE_ND,               "" );
	r_lodCurveError =                  ri.Cvar_Get( "r_lodCurveError",                  "250",                            CVAR_ARCHIVE_ND,               "" );
	r_lodscale =                       ri.Cvar_Get( "r_lodscale",                       "5",                              CVAR_NONE,                     "" );
	r_logFile =                        ri.Cvar_Get( "r_logFile",                        "0",                              CVAR_CHEAT,                    "" );
	r_mapOverBrightBits =              ri.Cvar_Get( "r_mapOverBrightBits",              "0",                              CVAR_ARCHIVE_ND | CVAR_LATCH,  "" );
	r_markcount =                      ri.Cvar_Get( "r_markcount",                      "100",                            CVAR_ARCHIVE_ND,               "" );
	r_marksOnTriangleMeshes =          ri.Cvar_Get( "r_marksOnTriangleMeshes",          "0",                              CVAR_ARCHIVE_ND,               "" );
	r_maxpolys =                       ri.Cvar_Get( "r_maxpolys",                       XSTRING( DEFAULT_MAX_POLYS ),     CVAR_NONE,                     "" );
	r_maxpolyverts =                   ri.Cvar_Get( "r_maxpolyverts",                   XSTRING( DEFAULT_MAX_POLYVERTS ), CVAR_NONE,                     "" );
	r_measureOverdraw =                ri.Cvar_Get( "r_measureOverdraw",                "0",                              CVAR_CHEAT,                    "" );
	r_mode =                           ri.Cvar_Get( "r_mode",                           "4",                              CVAR_ARCHIVE | CVAR_LATCH,     "" );
	r_modelpoolmegs =                  ri.Cvar_Get( "r_modelpoolmegs",                  "20",                             CVAR_ARCHIVE,                  "" );
	r_nobind =                         ri.Cvar_Get( "r_nobind",                         "0",                              CVAR_CHEAT,                    "" );
	r_noborder =                       ri.Cvar_Get( "r_noborder",                       "0",                              CVAR_ARCHIVE | CVAR_LATCH,     "" );
	r_nocull =                         ri.Cvar_Get( "r_nocull",                         "0",                              CVAR_CHEAT,                    "" );
	r_nocurves =                       ri.Cvar_Get( "r_nocurves",                       "0",                              CVAR_CHEAT,                    "" );
	r_noportals =                      ri.Cvar_Get( "r_noportals",                      "0",                              CVAR_CHEAT,                    "" );
	r_norefresh =                      ri.Cvar_Get( "r_norefresh",                      "0",                              CVAR_CHEAT,                    "" );
	r_noServerGhoul2 =                 ri.Cvar_Get( "r_noServerGhoul2",                 "0",                              CVAR_NONE,                     "" );
	r_novis =                          ri.Cvar_Get( "r_novis",                          "0",                              CVAR_CHEAT,                    "" );
	r_offsetFactor =                   ri.Cvar_Get( "r_offsetFactor",                   "-1",                             CVAR_CHEAT,                    "" );
	r_offsetUnits =                    ri.Cvar_Get( "r_offsetUnits",                    "-2",                             CVAR_CHEAT,                    "" );
	r_overBrightBits =                 ri.Cvar_Get( "r_overBrightBits",                 "0",                              CVAR_ARCHIVE_ND | CVAR_LATCH,  "" );
	r_picmip =                         ri.Cvar_Get( "r_picmip",                         "0",                              CVAR_ARCHIVE | CVAR_LATCH,     "" );
	r_portalOnly =                     ri.Cvar_Get( "r_portalOnly",                     "0",                              CVAR_CHEAT,                    "" );
	r_primitives =                     ri.Cvar_Get( "r_primitives",                     "0",                              CVAR_ARCHIVE_ND,               "" );
	r_roofCeilFloorDist =              ri.Cvar_Get( "r_roofCeilFloorDist",              "128",                            CVAR_CHEAT,                    "" ); //attempted smart method of culling out upwards facing surfaces on roofs for automap shots -rww
	r_roofCullCeilDist =               ri.Cvar_Get( "r_roofCullCeilDist",               "256",                            CVAR_CHEAT,                    "" ); //attempted smart method of culling out upwards facing surfaces on roofs for automap shots -rww
	r_screenshotJpegQuality =          ri.Cvar_Get( "r_screenshotJpegQuality",          "95",                             CVAR_ARCHIVE_ND,               "" );
	r_shadowRange =                    ri.Cvar_Get( "r_shadowRange",                    "1000",                           CVAR_NONE,                     "" );
	r_showcluster =                    ri.Cvar_Get( "r_showcluster",                    "0",                              CVAR_CHEAT,                    "" );
	r_showFrameVariance =              ri.Cvar_Get( "r_showFrameVariance",              "0",                              CVAR_NONE,                     "" );
	r_showImages =                     ri.Cvar_Get( "r_showImages",                     "0",                              CVAR_CHEAT,                    "" );
	r_shownormals =                    ri.Cvar_Get( "r_shownormals",                    "0",                              CVAR_CHEAT,                    "" );
	r_showsky =                        ri.Cvar_Get( "r_showsky",                        "0",                              CVAR_CHEAT,                    "" );
	r_showtris =                       ri.Cvar_Get( "r_showtris",                       "0",                              CVAR_CHEAT,                    "" );
	r_simpleMipMaps =                  ri.Cvar_Get( "r_simpleMipMaps",                  "1",                              CVAR_ARCHIVE_ND | CVAR_LATCH,  "" );
	r_singleShader =                   ri.Cvar_Get( "r_singleShader",                   "0",                              CVAR_CHEAT | CVAR_LATCH,       "" );
	r_skipBackEnd =                    ri.Cvar_Get( "r_skipBackEnd",                    "0",                              CVAR_CHEAT,                    "" );
	r_speeds =                         ri.Cvar_Get( "r_speeds",                         "0",                              CVAR_CHEAT,                    "" );
	r_subdivisions =                   ri.Cvar_Get( "r_subdivisions",                   "4",                              CVAR_ARCHIVE_ND | CVAR_LATCH,  "" );
	r_surfaceSprites =                 ri.Cvar_Get( "r_surfaceSprites",                 "1",                              CVAR_ARCHIVE_ND,               "" );
	r_surfaceWeather =                 ri.Cvar_Get( "r_surfaceWeather",                 "0",                              CVAR_TEMP,                     "" );
	r_terrainTessellate =              ri.Cvar_Get( "r_terrainTessellate",              "3",                              CVAR_CHEAT,                    "" );
	r_terrainWaterOffset =             ri.Cvar_Get( "r_terrainWaterOffset",             "0",                              CVAR_NONE,                     "" );
	r_texturebits =                    ri.Cvar_Get( "r_texturebits",                    "0",                              CVAR_ARCHIVE_ND | CVAR_LATCH,  "" );
	r_texturebitslm =                  ri.Cvar_Get( "r_texturebitslm",                  "0",                              CVAR_ARCHIVE_ND | CVAR_LATCH,  "" );
	r_textureMode =                    ri.Cvar_Get( "r_textureMode",                    "GL_LINEAR_MIPMAP_LINEAR",        CVAR_ARCHIVE,                  "" );
	r_uiFullScreen =                   ri.Cvar_Get( "r_uiFullScreen",                   "1",                              CVAR_NONE,                     "" );
	r_verbose =                        ri.Cvar_Get( "r_verbose",                        "0",                              CVAR_CHEAT,                    "" );
	r_vertexLight =                    ri.Cvar_Get( "r_vertexLight",                    "0",                              CVAR_ARCHIVE | CVAR_LATCH,     "" );
	r_windAngle =                      ri.Cvar_Get( "r_windAngle",                      "0",                              CVAR_NONE,                     "" );
	r_windDampFactor =                 ri.Cvar_Get( "r_windDampFactor",                 "0.1",                            CVAR_NONE,                     "" );
	r_windGust =                       ri.Cvar_Get( "r_windGust",                       "0",                              CVAR_NONE,                     "" );
	r_windPointForce =                 ri.Cvar_Get( "r_windPointForce",                 "0",                              CVAR_NONE,                     "" );
	r_windPointX =                     ri.Cvar_Get( "r_windPointX",                     "0",                              CVAR_NONE,                     "" );
	r_windPointY =                     ri.Cvar_Get( "r_windPointY",                     "0",                              CVAR_NONE,                     "" );
	r_windSpeed =                      ri.Cvar_Get( "r_windSpeed",                      "0",                              CVAR_NONE,                     "" );
	r_znear =                          ri.Cvar_Get( "r_znear",                          "4",                              CVAR_ARCHIVE_ND,               "" );
	se_language =                      ri.Cvar_Get( "se_language",                      "english",                        CVAR_ARCHIVE | CVAR_NORESTART, "" );
	sv_pure =                          ri.Cvar_Get( "sv_pure",                          "0",                              CVAR_SYSTEMINFO,               "Pure server" );
	timescale =                        ri.Cvar_Get( "timescale",                        "1",                              CVAR_CHEAT | CVAR_SYSTEMINFO,  "" );

	ri.Cvar_CheckRange( r_picmip,                0,              16,             true );
	ri.Cvar_CheckRange( r_subdivisions,          0,              80,             false );
	ri.Cvar_CheckRange( r_znear,                 0.001f,         10,             false );
	ri.Cvar_CheckRange( r_primitives,            MIN_PRIMITIVES, MAX_PRIMITIVES, true );
	ri.Cvar_CheckRange( r_aviMotionJpegQuality,  10,             100,            true );
	ri.Cvar_CheckRange( r_screenshotJpegQuality, 10,             100,            true );
}
